name: 'Build DBus'
description: 'Clone and build DBus'

inputs:
  os:
    description: "Runner OS"
    default: ''
    required: false

  arch:
    description: "Platform architecture"
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -H apt-get remove -y libexpat1-dev

    - name: Get latest Expat commit hash
      id: expat-hash
      shell: bash
      # NOTE: Pinning libexpat to 2.7.0 as the exact version is not important.
      run: |
        EXPAT_HASH=6d4ffe856df497ac2cae33537665c3fec7ec8a00
        echo "value=$EXPAT_HASH" >> $GITHUB_OUTPUT

    # - name: Cache Expat
    #   id: cache-expat
    #   uses: actions/cache@v4
    #   with:
    #     path: /tmp/install/expat
    #     key: ${{ inputs.os }}-${{ inputs.arch }}-expat-${{ steps.expat-hash.outputs.value }}

    - name: Build Expat
      if: steps.cache-expat.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone https://github.com/libexpat/libexpat.git /tmp/expat
        cd /tmp/expat/expat
        git checkout ${{ steps.expat-hash.outputs.value }}
        cmake -B build -DEXPAT_BUILD_DOCS=OFF -DEXPAT_BUILD_EXAMPLES=OFF -DEXPAT_BUILD_TESTS=OFF
        cmake --build build --config Release --parallel 4
        cmake --install build --prefix /tmp/install/expat

    - name: Get latest DBus commit hash
      id: dbus-hash
      shell: bash
      # NOTE: Pinning DBus to 1.16.2 as the exact version is not important.
      run: |
        DBUS_HASH=958bf9db2100553bcd2fe2a854e1ebb42e886054
        echo "value=$DBUS_HASH" >> $GITHUB_OUTPUT

    # - name: Cache DBus
    #   id: cache-dbus
    #   uses: actions/cache@v4
    #   with:
    #     path: /tmp/install/dbus
    #     key: ${{ inputs.os }}-${{ inputs.arch }}-dbus-${{ steps.dbus-hash.outputs.value }}

    - name: Build DBus
      if: steps.cache-dbus.outputs.cache-hit != 'true'
      shell: bash
      # NOTE: The build step requires us to extend the CMAKE_FIND_ROOT_PATH to include the expat install path,
      #       as cross-compilation environments will ignore CMAKE_PREFIX_PATH.
      run: |
        git clone https://gitlab.freedesktop.org/dbus/dbus.git /tmp/dbus
        cd /tmp/dbus
        git checkout ${{ steps.dbus-hash.outputs.value }}
        cmake -B build -DDBUS_SESSION_SOCKET_DIR=/usr/local/var/run/dbus/system_bus_socket -DDBUS_BUILD_TESTS=OFF -DCMAKE_PREFIX_PATH=/tmp/install/expat
        cmake --build build --config Release --parallel 4
        cmake --install build --prefix /tmp/install/dbus
