name: 'Package Native Target'
description: 'Packages a directory into a ZIP file for Linux, macOS, or Windows using zip.'

inputs:
  source-dir:
    description: 'Path to the directory to package (e.g., build/install)'
    required: true
  output-dir:
    description: 'Directory where the ZIP file will be created (e.g., artifacts)'
    required: true
  archive-name:
    description: 'Name of the output ZIP file (without .zip extension)'
    required: true
  os:
    description: 'Operating system (linux, macos, or windows) to determine shell and command'
    required: true

runs:
  using: "composite"
  steps:
    - name: Package Directory (Linux/macOS)
      if: inputs.os == 'linux' || inputs.os == 'macos'
      shell: bash
      run: |
        mkdir -p "${{ inputs.output-dir }}"
        cd "${{ inputs.source-dir }}"
        zip -r "${{ inputs.output-dir }}/${{ inputs.archive-name }}.zip" .

    - name: Package Directory (Windows)
      if: inputs.os == 'windows'
      shell: bash
      run: |
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "Raw source-dir: ${{ inputs.source-dir }}"
        echo "Raw output-dir: ${{ inputs.output-dir }}"
        echo -e "\nContents of GitHub workspace:"
        find "$GITHUB_WORKSPACE" -type f
        echo -e "\nContents of build directory (if it exists):"
        if [ -d "$GITHUB_WORKSPACE/build_simpleble" ]; then
            find "$GITHUB_WORKSPACE/build_simpleble" -type f
        else
            echo "build_simpleble directory does not exist"
        fi

        mkdir -p "${{ inputs.output-dir }}"
        cd "${{ inputs.source-dir }}"
        zip -r "${{ inputs.output-dir }}/${{ inputs.archive-name }}.zip" .