name: Build JNI

on:
  workflow_dispatch:
  workflow_call:  # Allows this to be called from other workflows

jobs:
  build-jni-dependencies:
    runs-on: ${{ matrix.config.runner-os || 'ubuntu-latest' }} # Fallback runner
    container: ${{ matrix.config.container-image }} # Use container if specified
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux, target: linux-x64, architecture: x64, container-image: dockcross/linux-x64 }
          - { runner-os: ubuntu-22.04, os: linux, target: linux-aarch64, architecture: aarch64, container-image: dockcross/linux-arm64 }
          - { runner-os: macos-14, os: macos, target: macos-aarch64, architecture: aarch64 } # Containers are not required.
          - { runner-os: windows-2022, os: windows, target: windows-x64, architecture: x64 } # Containers are not required.

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: ${{ matrix.config.architecture }}

      - name: Setup Environment (Linux)
        if: matrix.config.os == 'linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -H apt-get update -y
          sudo -H apt-get install -y libdbus-1-dev

      - name: Setup Environment (Windows)
        if: matrix.config.os == 'windows'
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup CMake (macOS)
        if: matrix.config.os == 'macos'
        uses: ./.github/actions/setup-cmake

      - name: Build SimpleBLE Library
        uses: ./.github/actions/build-native
        with:
          source-dir: "$GITHUB_WORKSPACE/simplejavable/cpp"
          build-dir: "$GITHUB_WORKSPACE/build_simplejavable"
          build-config: "Release"
          os: "${{ matrix.config.os }}"
          target-arch: "${{ matrix.config.architecture }}"
          cmake-options: ""  # No additional options needed; handled by the action

      - name: Upload JNI Binaries
        if: matrix.config.os != 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: libsimplejavable_${{ matrix.config.architecture }}_${{ matrix.config.target }}
          path: build_simplejavable/lib/libsimplejavable*

      - name: Upload JNI Binaries
        if: matrix.config.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: libsimplejavable_${{ matrix.config.architecture }}_${{ matrix.config.target }}
          path: build_simplejavable/bin/Release/simplejavable*

  build-jar:
    runs-on: ubuntu-22.04
    needs: build-jni-dependencies
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: "Download JNI Binaries"
        uses: actions/download-artifact@v4
        with:
          pattern: 'libsimplejavable*'
          path: 'jni_download'

      - name: Rename JNI Directories
        working-directory: ${{ github.workspace }}/jni_download
        run: |
          mkdir -p $GITHUB_WORKSPACE/jni
          for dir in libsimplejavable_*; do
            # Extract architecture (e.g., 'amd64' from 'libsimplejavable_amd64_linux-x64')
            arch=$(echo "$dir" | sed 's/libsimplejavable_//;s/_[^_]*$//')
            mkdir -p $GITHUB_WORKSPACE/jni/$arch
            mv "$dir" "$GITHUB_WORKSPACE/jni/$arch"
          done

      - name: List downloaded files
        run: find $GITHUB_WORKSPACE/jni -type f -ls

      - name: Build SimpleJavaBLE Java Library
        run: |
          gradle -p simplejavable/java -PnativeLibPath=$GITHUB_WORKSPACE/jni -Dorg.gradle.project.buildDir=$GITHUB_WORKSPACE/artifacts --no-daemon build

      - name: Upload SimpleJavaBLE Java Library
        uses: actions/upload-artifact@v4
        with:
          name: simplejavable.jar
          path: artifacts/libs/simplejavable*.jar