name: CI Build Demo

on:
  workflow_dispatch:
  workflow_call:  # Allows this to be called from other workflows

jobs:
  build:
    runs-on: ${{ matrix.config.runner-os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux }
          - { runner-os: macos-14, os: macos }
          - { runner-os: windows-2022, os: windows }

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Environment (Linux)
        if: matrix.config.os == 'linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -H apt-get update -y
          sudo -H apt-get install -y libdbus-1-dev

      - name: Setup Environment (Windows)
        if: matrix.config.os == 'windows'
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup CMake (macOS)
        if: matrix.config.os == 'macos'
        uses: ./.github/actions/setup-cmake

      - name: Build SimpleBLE Library
        uses: ./.github/actions/build-native
        with:
          source-dir: "$GITHUB_WORKSPACE/simpleble"
          build-dir: "$GITHUB_WORKSPACE/build_simpleble"
          install-prefix: "$GITHUB_WORKSPACE/build_simpleble/install"
          build-config: "Release"
          library-type: "static"
          os: "${{ matrix.config.os }}"
          cmake-options: ""  # No additional options needed; handled by the action
