name: Build SimpleBLE

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.config.runner-os || 'ubuntu-latest' }}
    container: ${{ matrix.config.container-image }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux, architecture: x64, container-image: dockcross/linux-x64 }
          - { runner-os: ubuntu-22.04, os: linux, architecture: x86, container-image: dockcross/linux-x86 }
          - { runner-os: ubuntu-22.04, os: linux, architecture: aarch64, container-image: dockcross/linux-arm64 }
          - { runner-os: ubuntu-22.04, os: linux, architecture: armv6, container-image: dockcross/linux-armv6-lts }
          - { runner-os: macos-14, os: macos, architecture: x64 } # Containers are not required.
          - { runner-os: macos-14, os: macos, architecture: aarch64 } # Containers are not required.
          - { runner-os: macos-14, os: ios, architecture: aarch64 } # Containers are not required.
          - { runner-os: windows-2022, os: windows, architecture: x64 } # Containers are not required.
          - { runner-os: windows-2022, os: windows, architecture: x86 } # Containers are not required.

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Build SimpleBLE Library (Static)
        uses: ./.github/actions/build-native
        with:
          source-dir: "$GITHUB_WORKSPACE/simpleble"
          build-dir: "$GITHUB_WORKSPACE/build_simpleble_static"
          install-prefix: "$GITHUB_WORKSPACE/install_simpleble/static"
          build-config: "Release"
          library-type: "static"
          os: "${{ matrix.config.os }}"
          target-arch: "${{ matrix.config.architecture }}"
          cmake-options: ""

      - name: Build SimpleBLE Library (Shared)
        uses: ./.github/actions/build-native
        with:
          source-dir: "$GITHUB_WORKSPACE/simpleble"
          build-dir: "$GITHUB_WORKSPACE/build_simpleble_shared"
          install-prefix: "$GITHUB_WORKSPACE/install_simpleble/shared"
          build-config: "Release"
          library-type: "shared"
          os: "${{ matrix.config.os }}"
          target-arch: "${{ matrix.config.architecture }}"
          cmake-options: ""

      - name: List Files in Install Directory
        shell: bash
        if: matrix.config.os == 'ios'
        run: |
          echo "Listing all files in install_simpleble directory for iOS:"
          find $GITHUB_WORKSPACE/install_simpleble -type f | sort

      - name: Package SimpleBLE Artifact
        uses: ./.github/actions/package-native
        with:
          source-dir: $GITHUB_WORKSPACE/install_simpleble
          output-dir: $GITHUB_WORKSPACE/artifacts
          archive-name: libsimpleble_${{ matrix.config.os }}-${{ matrix.config.architecture }}
          os: "${{ matrix.config.os }}"

      - name: List Files in Artifact Directory
        shell: bash
        if: matrix.config.os == 'ios'
        run: |
          echo "Listing all files in artifacts directory:"
          find $GITHUB_WORKSPACE/artifacts -type f | sort

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: libsimpleble_${{ matrix.config.os }}-${{ matrix.config.architecture }}
          path: artifacts/libsimpleble_${{ matrix.config.os }}-${{ matrix.config.architecture }}.zip