name: CI Build Demo

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.config.runner-os || 'ubuntu-latest' }}
    container: ${{ matrix.config.container-image }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux, architecture: x64, container-image: dockcross/linux-x64 }
          # - { runner-os: ubuntu-22.04, os: linux, architecture: x86, container-image: dockcross/linux-x86 }
          # - { runner-os: ubuntu-22.04, os: linux, architecture: aarch64, container-image: dockcross/linux-arm64 }
          # - { runner-os: ubuntu-22.04, os: linux, architecture: armv6, container-image: dockcross/linux-armv6-lts }
          # - { runner-os: macos-14, os: macos, architecture: x64 } # Containers are not required.
          # - { runner-os: macos-14, os: macos, architecture: aarch64 } # Containers are not required.
          # - { runner-os: macos-14, os: ios, architecture: aarch64 } # Containers are not required.
          # - { runner-os: windows-2022, os: windows, architecture: x64 } # Containers are not required.
          # - { runner-os: windows-2022, os: windows, architecture: x86 } # Containers are not required.

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo -H apt-get update -y
          sudo -H apt-get install -y libdbus-1-dev
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Setup cmake
        uses: ./.github/actions/setup-cmake

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Compile SimpleBLE
        run: cargo build
