name: CI Build Demo

on:
  workflow_dispatch:
  workflow_call:  # Allows this to be called from other workflows

jobs:
  build:
    runs-on: ${{ matrix.config.runner-os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux, architecture: x64 }
          - { runner-os: macos-14, os: macos, architecture: x64 }
          - { runner-os: macos-14, os: ios, architecture: aarch64 }
          - { runner-os: windows-2022, os: windows, architecture: x64 }

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Build SimpleBLE Library
        uses: ./.github/actions/build-native
        with:
          source-dir: "$GITHUB_WORKSPACE/simpleble"
          build-dir: "$GITHUB_WORKSPACE/build_simpleble"
          install-prefix: "$GITHUB_WORKSPACE/build_simpleble/install"
          build-config: "Release"
          library-type: "static"
          os: "${{ matrix.config.os }}"
          target-arch: "${{ matrix.config.architecture }}"
          cmake-options: ""  # No additional options needed; handled by the action
