name: Build SimpleDroidBLE

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build-lib:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build simplebledroidble AAR
        run: gradle :bundleReleaseAar -p ./simpledroidble --no-daemon -Dorg.gradle.project.buildDir="$GITHUB_WORKSPACE/build_simpledroidble"

      - name: Package Artifact
        uses: ./.github/actions/package-native
        with:
          source-dir: $GITHUB_WORKSPACE/build_simpledroidble/outputs/aar
          output-dir: $GITHUB_WORKSPACE/artifacts
          archive-name: simpledroidble
          os: linux

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: simpledroidble
          path: artifacts/simpledroidble.zip

  build-examples:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build simplebledroidble examples AAR
        run: gradle :bundleReleaseAar -p ./examples/simpleble-android --no-daemon -Dorg.gradle.project.buildDir="$GITHUB_WORKSPACE/build_simpledroidble_examples"

      - name: Package Artifact
        uses: ./.github/actions/package-native
        with:
          source-dir: $GITHUB_WORKSPACE/build_simpledroidble_examples/outputs/aar
          output-dir: $GITHUB_WORKSPACE/artifacts
          archive-name: simpledroidble_examples
          os: linux

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: simpledroidble_examples
          path: artifacts/simpledroidble_examples.zip